[package]
name = "wlw-common"
version = "0.1.0"
authors = ["Eliza Velasquez <elizagamedev@gmail.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.*", features = ["windef", "winuser"] }
